#!/usr/bin/env ruby
require 'pathname'

Dir.glob("*.sh").each do |file|
  script = Pathname.new(file)
  signed_script = Pathname.new("#{file}.sig")
  if !signed_script.exist? || script.mtime >= signed_script.mtime
    command = "gpg -u justin@bulletprooftiger.com --output #{signed_script} --sign #{script}"
    puts "#{script} has changed.  Updating signature:"
    `#{command}`
  else
    puts "Skipping #{script}"
  end
end
